services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: meteor-bt-api
        environment:
            PORT: 80
            DB_HOST: cassandra
            DB_DATA_CENTER: datacenter1
            DB_KEYSPACE: weather_data
        ports:
            - "8000:80"
        networks:
            - cassandra

networks:
    cassandra:
        external: true
