version: "3.8"

services:
    api:
        image: sifatulrabbi/meteor-bt-api:0.1.0-dev
        environment:
            PORT: 8000
            DB_HOST: 127.0.0.1
            DB_DATA_CENTER: datacenter1
            DB_KEYSPACE: weather_data
        ports:
            - "8000:8000"
        network_mode: "host"
