services:
    api:
        image: sifatulrabbi/meteor-bt-api:0.1.1-dev
        container_name: meteor-bt-api
        env_file: .env
        ports:
            - "8000:8000"
        networks:
            - cassandra

networks:
    cassandra:
        external: true
